### ISSUE TITLE
Additional Documentation

### ISSUE THREAD

**Issue by razzam21** [grocy/grocy-pyscanner#1]
Can you please provide some additional documentation on where to put this script? I have read through the script and have a decent idea of how it works but I am not sure where to put it so that I can use it.

**Comment by TheFuzz4** [comment]
Yes I can.  So I'll put this in here for you and then I'll update the readme.  So in my case I put this script on a Raspberry Pi.  Because its just making web calls to both the UPC databases as well as grocy you can really put this script wherever you like.  I did it on the pi because that is where I plugged in the USB barcode scanner into.  You could run it on your laptop if you'd like.  It does not have to live on the same machine that is running grocy thats the beauty of the api calls.  I apologize it took me so long to get back to you I never got a notification from github that this issue was filed.
